export const screenshotFixtures = [
  {
    id: 'research-brief-writer',
    type: 'skill',
    name: '行业研究简报',
    version: '1.3.0',
    description: '汇总公开资料，提炼行业趋势、关键数据与竞争格局，生成结构化研究简报。',
    tags: ['研究', '报告', '数据分析'],
    author: '企业研究院',
    reviewStatus: 'approved',
    publishedAt: '2026-08-05T08:30:00Z',
    updatedAt: '2026-08-05T08:30:00Z',
    downloadCount: 2386,
    favoriteCount: 326,
    positiveRate: 96,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'meeting-minutes-pro',
    type: 'skill',
    name: '智能会议纪要',
    version: '2.1.2',
    description: '自动整理会议内容，识别决策事项、负责人和截止时间，并输出待办清单。',
    tags: ['会议', '效率', '总结'],
    author: '协同办公团队',
    reviewStatus: 'approved',
    publishedAt: '2026-08-04T03:15:00Z',
    updatedAt: '2026-08-04T03:15:00Z',
    downloadCount: 5128,
    favoriteCount: 714,
    positiveRate: 98,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'contract-risk-checker',
    type: 'skill',
    name: '合同风险检查',
    version: '1.0.8',
    description: '识别合同中的关键条款、潜在风险和缺失内容，辅助完成签署前检查。',
    tags: ['合同', '合规', '风险'],
    author: '法务数字化中心',
    reviewStatus: 'approved',
    publishedAt: '2026-08-03T10:20:00Z',
    updatedAt: '2026-08-03T10:20:00Z',
    downloadCount: 1842,
    favoriteCount: 255,
    positiveRate: 94,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'data-insight-assistant',
    type: 'skill',
    name: '经营数据洞察',
    version: '1.6.0',
    description: '分析经营指标变化，定位异常波动，并生成面向管理层的洞察摘要。',
    tags: ['经营分析', '指标', '洞察'],
    author: '数据智能平台',
    reviewStatus: 'approved',
    publishedAt: '2026-08-02T06:45:00Z',
    updatedAt: '2026-08-02T06:45:00Z',
    downloadCount: 3260,
    favoriteCount: 481,
    positiveRate: 97,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'customer-service-agent',
    type: 'agent',
    name: '智能客服专员',
    version: '2.4.1',
    description: '基于企业知识库回答客户问题，自动识别意图并将复杂问题转交人工处理。',
    tags: ['客服', '知识库', '自动应答'],
    author: '客户体验中心',
    reviewStatus: 'approved',
    publishedAt: '2026-08-05T02:00:00Z',
    updatedAt: '2026-08-05T02:00:00Z',
    downloadCount: 6482,
    favoriteCount: 903,
    positiveRate: 98,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'recruiting-copilot-agent',
    type: 'agent',
    name: '招聘协作助手',
    version: '1.8.3',
    description: '协助筛选简历、生成面试提纲，并汇总多位面试官的评价与录用建议。',
    tags: ['招聘', '简历', '面试'],
    author: '人力资源科技组',
    reviewStatus: 'approved',
    publishedAt: '2026-08-01T09:10:00Z',
    updatedAt: '2026-08-01T09:10:00Z',
    downloadCount: 2975,
    favoriteCount: 438,
    positiveRate: 95,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'operations-daily-agent',
    type: 'agent',
    name: '运营日报智能体',
    version: '1.2.0',
    description: '自动汇总渠道数据、业务进展和异常事项，每日生成可直接发送的运营日报。',
    tags: ['运营', '日报', '自动化'],
    author: '增长运营团队',
    reviewStatus: 'approved',
    publishedAt: '2026-07-30T04:25:00Z',
    updatedAt: '2026-07-30T04:25:00Z',
    downloadCount: 2140,
    favoriteCount: 319,
    positiveRate: 96,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
  {
    id: 'project-manager-agent',
    type: 'agent',
    name: '项目管理智能体',
    version: '3.0.0',
    description: '跟踪项目里程碑、风险与资源情况，主动提醒延期任务并生成项目周报。',
    tags: ['项目管理', '协作', '风险预警'],
    author: '研发效能团队',
    reviewStatus: 'approved',
    publishedAt: '2026-07-28T07:40:00Z',
    updatedAt: '2026-07-28T07:40:00Z',
    downloadCount: 4531,
    favoriteCount: 672,
    positiveRate: 97,
    metadata: {},
    assets: {},
    targets: {},
    dependencies: [],
  },
];
